services:
  website:
    image: ${WEBSITE_IMAGE_REPO}:${WEBSITE_IMAGE_TAG}
    restart: always
    env_file:
      - ${WEBSITE_ENV_FILE_PATH}
    environment:
      PORT: ${WEBSITE_PORT}
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}

  backend-api:
    image: ${BACKEND_API_IMAGE_REPO}:${BACKEND_API_IMAGE_TAG}
    restart: always
    environment:
      PORT: ${BACKEND_API_PORT}
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
