services:
  website:
    image: chenaski/image-compressor-website:${WEBSITE_IMAGE_TAG}
    restart: always
    environment:
      PORT: ${WEBSITE_PORT}
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}

  backend-api:
    image: chenaski/image-compressor-backend-api:${BACKEND_API_IMAGE_TAG}
    restart: always
    environment:
      PORT: ${BACKEND_API_PORT}
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
