services:
  website:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
    env_file:
      - apps/website/.env
    environment:
      PORT: ${WEBSITE_PORT}
      API_HOST: backend-api
      API_PORT: ${BACKEND_API_PORT}
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}

  backend-api:
    build:
      context: .
      dockerfile: apps/backend-api/Dockerfile
    environment:
      PORT: ${BACKEND_API_PORT}
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}

  image-processor:
    build:
      context: .
      dockerfile: apps/image-processor/Dockerfile
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning
