services:
  webserver:
    image: nginx:1-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .docker/nginx/conf:/etc/nginx/conf.d
      - .docker/nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - .docker/nginx/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem
      - ${CERTBOT_PATH}/conf:/etc/letsencrypt:ro
      - ${CERTBOT_PATH}/www:/var/www/certbot:ro

  website:
    image: ${WEBSITE_IMAGE_REPO}:${WEBSITE_IMAGE_TAG}
    restart: always
    env_file:
      - ${WEBSITE_ENV_FILE_PATH}
    environment:
      PORT: ${WEBSITE_PORT}
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}

  backend-api:
    image: ${BACKEND_API_IMAGE_REPO}:${BACKEND_API_IMAGE_TAG}
    restart: always
    environment:
      PORT: ${BACKEND_API_PORT}
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
