services:
  website:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
    env_file:
      - apps/website/.env
    environment:
      PORT: ${WEBSITE_PORT}
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}

  backend-api:
    build:
      context: .
      dockerfile: apps/backend-api/Dockerfile
    environment:
      PORT: ${BACKEND_API_PORT}
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
